<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find twinfork_description)/urdf/common_properties.urdf.xacro" />

    <xacro:macro name="drive_wheel" params="prefix x_off y_off base_prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <xacro:insert_block name="material_white" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial mass="1.0" radius="${wheel_radius}" length="${wheel_width}">
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </xacro:cylinder_inertial>
        </link>
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${base_prefix}base_link" />
            <child link="${prefix}_wheel_link" />
            <origin xyz="${x_off} ${y_off} ${-wheel_zoff}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
        <gazebo reference="${prefix}_wheel_link">
            <mu1>10.0</mu1>
            <mu2>10.0</mu2>
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="caster_wheel" params="prefix x_off base_prefix color='Gazebo/Black'">
        <link name="${prefix}_caster_link">
            <visual>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <xacro:insert_block name="material_white" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
            </collision>
            <xacro:sphere_inertial mass="0.1" radius="${caster_radius}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:sphere_inertial>
        </link>
        <joint name="${prefix}_caster_joint" type="fixed">
            <parent link="${base_prefix}base_link" />
            <child link="${prefix}_caster_link" />
            <origin xyz="${x_off} 0 ${-(wheel_radius+wheel_zoff-caster_radius-0.0001)}" rpy="0 0 0" />
        </joint>
        <gazebo reference="${prefix}_caster_link">
            <mu1>0.0</mu1>
            <mu2>0.0</mu2>
            <material>${color}</material>
        </gazebo>
    </xacro:macro>
</robot>