<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- See https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Diff-drive for ros2 information -->
  <xacro:macro name="diff_controller_plugin_gazebo" params="prefix ns left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
    <gazebo>
      <!-- Use gazebo_ros_joint_state_publisher instead of publishWheelJointState -->
      <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
        <ros>
          <namespace>${ns}</namespace>
        </ros>
        <update_rate>1000.0</update_rate>
        <joint_name>${right_wheel_joint}</joint_name>
        <joint_name>${left_wheel_joint}</joint_name>
      </plugin>

      <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <namespace>${ns}</namespace>
          <remapping>cmd_vel:=cmd_vel</remapping>
          <remapping>odom:=odom</remapping>
        </ros>

        <legacy_mode>false</legacy_mode>
        <!-- 0 = encoder integration, 1 = world-pose (ground truth, default) -->
        <odometry_source>1</odometry_source>
        <always_on>true</always_on>

        <update_rate>1000.0</update_rate>
        <left_joint>${left_wheel_joint}</left_joint>
        <right_joint>${right_wheel_joint}</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${2*wheel_radius}</wheel_diameter>
        <odometry_frame>${prefix}odom</odometry_frame>

        <robot_base_frame>${prefix}base_footprint</robot_base_frame>
        <publish_odom>true</publish_odom>
        <publish_wheel_tf>false</publish_wheel_tf>
        <publish_odom_tf>true</publish_odom_tf>

        <max_wheel_torque>100</max_wheel_torque>
        <max_wheel_acceleration>10.0</max_wheel_acceleration>

      </plugin>
    </gazebo>
  </xacro:macro>
</robot>